project:
  type: website
  output-dir: docs

website:
  title: "CS 5805: Machine Learning Course Project"
  navbar:
    left:
      - href: index.qmd
        text: Random Variables and Probability Theory
      - about.qmd
      - blog3.qmd
      - blog4.qmd
      - blog5.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



