project:
  type: website
  output-dir: docs

website:
  title: "CS 5805: Machine Learning Course Project"
  navbar:
    left:
      - href: index.qmd
        text: Linear Regression and Non-Linear Regressiion
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



